
// ------------------------------------------------------------------------
// Copyright (c) 2016-2019 Alexandre Bento Freire. All rights reserved.
// Licensed under the MIT License+uuid License. See License.txt for details
// ------------------------------------------------------------------------

/* spell-checker: disable */
define({
  'HISTORY_HINT': ' Use Ctrl+UP/DOWN to fetch the history',
  'SPACETEXT_HINT': ' use \\$ for leading and trimming spaces',
  'SHORTCUT_HINT': 'Ex: Ctrl-Shift-U (win).  Cmd-Shift-U (mac)',
  'NEED_RESTART_MSG': 'Only takes effect after restart!',
  'DEVBY_MSG': 'Developed by {0}',
  'EXTRACTOR_MSG': 'Write a regular expression<br>All matches will be copy to the clipboard<br>',
  'FLD_limaxcharsperline_label': 'Max Chars per line',
  'FLD_limaxcharsperline_hint': 'Set 0 to no word wrap',
  'FLD_maxcharsperline_label': 'Max Chars per line',
  'FLD_maxcharsperline_hint': 'Min is 1',
  'FLD_tobreakwords_label': 'Break words',
  'FLD_tobreakwords_hint': 'Set to true, if it can break words',
  'FLD_lihtmlparawrap_label': 'html tag wrap',
  'FLD_lihtmlparawrap_hint': 'Wraps each paragraph with this tag. Ex: p',
  'FLD_linrparagraphs_label': 'Nr Paragraphs',
  'FLD_linrparagraphs_hint': 'Maximum is 100',
  'FLD_scss_label': 'scss Compiler',
  'FLD_scss_hint': 'You Must install sass 1st. Goto http://sass-lang.com/. WARN: Some sass implementations use --source-map instead of  --sourcemap',
  'FLD_scss_compass_label': 'Compass',
  'FLD_scss_sass_label': 'SCSS',
  'FLD_scss_autosave_hint': 'AutoSave',
  'FLD_js6_label': 'js6 Compiler',
  'FLD_js6_hint': 'You must install nodejs, and then "npm install -g traceur"',
  'FLD_js6_autosave_hint': 'AutoSave',
  'FLD_js_label': 'js Compiler',
  'FLD_js_hint': 'You must install nodejs, and then "npm install -g uglify-js"',
  'FLD_splitMarker_label': 'Split Marker',
  'FLD_historySize_label': 'History Size',
  'FLD_recentSize_label': 'Recent Size',
  'FLD_showcxtedit_label': 'Show Edit commands on Context Menu',
  'FLD_showcxtedit_hint': 'Requires a reload to take effect',
  'FLD_startNum_label': 'Initial Value',
  'FLD_numSep_label': 'Separator after Number',
  'FLD_tabSize_label': 'Tab Size',
  'FLD_find_label': 'Find',
  'FLD_replace_label': 'Replace',
  'FLD_replace_hint': 'Use #{d}#, #{x}#, #{X}#, #{<value>d}#, #{0<value>d}# for numbering macro',
  'FLD_startValue_label': 'Start',
  'FLD_startValue_hint': 'Leave empty for no numbering, since it slows down the process and only supports a small regular expression subset replacement. Must have Regular Expression checked',
  'FLD_stepValue_label': 'Step',
  'FLD_iswordsonly_label': 'Words Only',
  'FLD_iswordsonly_hint': 'Only works if is not a regular expression',
  'FLD_isregexpr_label': 'Regular Expression',
  'FLD_isignorecase_label': 'Ignore Case',
  'FLD_isimultiline_label': 'Multiline',
  'FLD_isall_label': 'Replace All',
  'FLD_isselonly_label': 'Only Selection',
  'FLD_isselonly_hint': 'If there is a selected text, only replaces the selected text',
  'FLD_webSearch_label': 'Search Engine url',
  'HDR_options_Field_label': 'Field',
  'HDR_options_Value_label': 'Value',
  'HDR_options_ExecOnSave_label': 'Execute On Save',
  'HDR_commandsmapper_Command_label': 'Command',
  'HDR_commandsmapper_Hotkey_label': 'Hotkey',
  'HDR_commandsmapper_Show on Menu_label': 'Show on Menu',
  'HDR_commandsmapper_Show on CtxMenu_label': 'Show on CtxMenu',
  'FLD_Cmdline_label': 'Cmdline',
  'FLD_Path_label': 'Path',
  'FLD_Predefined_label': 'Predefined',
  'FLD_ShowOutput_label': 'Show Output',
  'CAT_General': 'General',
  'CAT_Compilers': 'Compilers',
  'CAT_Shortcuts': 'Shortcuts',
  'CAT_BeforeSave': 'Before Save',
  'CAT_AfterSave': 'After Save',
  'CAT_Tools': 'Tools',
  'CAT_Project': 'Project',
  'Extensions': 'Extensions',
  'UpperCase': 'UpperCase',
  'LowerCase': 'LowerCase',
  'Capitalize': 'Capitalize',
  'CamelCase': 'CamelCase',
  'DashCase': 'DashCase',
  'CycleCase': 'CycleCase',
  'HtmlEncode': 'HtmlEncode',
  'HtmlDecode': 'HtmlDecode',
  'UrlEncode': 'UrlEncode',
  'UrlDecode': 'UrlDecode',
  'Join': 'Join',
  'Split': 'Split',
  'Number': 'Number',
  'Reverse': 'Reverse',
  'Trim Leading': 'Trim Leading',
  'Trim Trailing': 'Trim Trailing',
  'Markdown Trim Trailing': 'Markdown Trim Trailing',
  'Sort Ascending': 'Sort Ascending',
  'Sort Descending': 'Sort Descending',
  'Remove Duplicates': 'Remove Duplicates',
  'Remove Empty Lines': 'Remove Empty Lines',
  'Unix To Win': 'Unix To Win Slash',
  'Win To Unix': 'Win To Unix Slash',
  'Single Slash To Double': 'Single Slash To Double',
  'Double To Single Slash': 'Double To Single Slash',
  'Single Quote To Double': 'Single Quote To Double',
  'Double To Single Quote': 'Double To Single Quote',
  'Toggle Quote': 'Toggle Quote',
  'Tab To Space': 'Tab To Space',
  'Space To Tab': 'Space To Tab',
  'Untag': 'Untag',
  'Tag': 'Tag',
  'Break Line At': 'Break Line At',
  'Function JSDoc': 'Function JSDoc',
  'Declare JSLint Global': 'Declare JSLint Global',
  'Extractor': 'Extractor',
  'Replace': 'Replace',
  'Open Url': 'Open Url',
  'Web Search': 'Web Search',
  'Browse File': 'Browse File',
  'Recent Files': 'Recent Files',
  'Copy Filename': 'Copy Filename',
  'Copy Fullname': 'Copy Fullname',
  'Html Report': 'Html Report',
  'Regex Tester': 'Regex Tester',
  'Compiler': 'Compile(js6, scss)',
  'Commands': 'Commands',
  'Commands Mapper': 'Commands Mapper',
  'Options': 'Options',
  'Execute': 'Execute'
});