// this is automatic generated file. Edit i18n-dev.tsv and run node txt2nls.js

// ------------------------------------------------------------------------
// Copyright (c) 2016-2019 Alexandre Bento Freire. All rights reserved.
// Licensed under the MIT License+uuid License. See License.txt for details
// ------------------------------------------------------------------------

/* spell-checker: disable */
define({
  'HISTORY_HINT': '使用Ctrl + UP / DOWN来获取历史纪录',
  'SPACETEXT_HINT': ' 使用 \\$ 来获取行初空白与行尾空白',
  'SHORTCUT_HINT': '例如：Ctrl-Shift-U (win). Cmd-Shift-U (mac)',
  'NEED_RESTART_MSG': '重新启动后生效！',
  'DEVBY_MSG': '通过{0}开发',
  'EXTRACTOR_MSG': '写出一个正则运算法<br>所有符合的项目将会复制到剪贴板<br>',
  'FLD_limaxcharsperline_label': '每行的最大值',
  'FLD_limaxcharsperline_hint': '设置0无自动换行',
  'FLD_maxcharsperline_label': '每行的最大值',
  'FLD_maxcharsperline_hint': '最小值为1',
  'FLD_tobreakwords_label': '断词',
  'FLD_tobreakwords_hint': '如果可以断词,设定为正确',
  'FLD_lihtmlparawrap_label': 'html tag wrap',
  'FLD_lihtmlparawrap_hint': '以此标签包裹每个段落。例如：p',
  'FLD_linrparagraphs_label': '段落号码',
  'FLD_linrparagraphs_hint': '最大值为100',
  'FLD_scss_label': 'scss编译器',
  'FLD_scss_hint': '您必须先安装sass。转到http://sass-lang.com/',
  'FLD_scss_compass_label': 'Compass',
  'FLD_scss_sass_label': 'SCSS',
  'FLD_scss_autosave_hint': '自动保存',
  'FLD_js6_label': 'js6编译器',
  'FLD_js6_hint': '您必须安装nodejs，然后"npm install -g traceur"',
  'FLD_js6_autosave_hint': '自动保存',
  'FLD_js_label': 'JS编译器',
  'FLD_js_hint': '您必须安装nodejs，然后"npm install -g uglify-js"',
  'FLD_splitMarker_label': '分裂标记',
  'FLD_historySize_label': '历史大小',
  'FLD_recentSize_label': '最近的大小',
  'FLD_showcxtedit_label': '按右键显示编辑命令',
  'FLD_showcxtedit_hint': '需要重新加载才能生效',
  'FLD_startNum_label': '初始值',
  'FLD_numSep_label': '号码后分离',
  'FLD_tabSize_label': '跳位字元大小',
  'FLD_find_label': '寻找',
  'FLD_replace_label': '取代',
  'FLD_replace_hint': '使用＃{d}＃，＃{d}＃，＃{d}＃，＃{<value> d}＃，＃{0 <value> d}＃为巨集编号',
  'FLD_startValue_label': '开始',
  'FLD_startValue_hint': '为无编号留空，因为它减慢过程而且只支持取代小的正则表达式子集。必须检查正则表达式',
  'FLD_stepValue_label': '步骤',
  'FLD_iswordsonly_label': '全字',
  'FLD_iswordsonly_hint': '只有在不是正则表达式时运作',
  'FLD_isregexpr_label': '正则表达式',
  'FLD_isignorecase_label': '忽略大小写',
  'FLD_isimultiline_label': '多线路',
  'FLD_isall_label': '全部取代',
  'FLD_isselonly_label': '选取范围内',
  'FLD_isselonly_hint': '如果有已选择的文本,取代已选择的文本',
  'FLD_webSearch_label': '搜索引擎网址',
  'HDR_options_Field_label': '栏位',
  'HDR_options_Value_label': '值',
  'HDR_options_ExecOnSave_label': '保存后执行',
  'HDR_commandsmapper_Command_label': '命令',
  'HDR_commandsmapper_Hotkey_label': '热键',
  'HDR_commandsmapper_Show on Menu_label': '显示于主选单',
  'HDR_commandsmapper_Show on CtxMenu_label': '按右键后显示',
  'FLD_Cmdline_label': '命令行',
  'FLD_Path_label': '路径',
  'FLD_Predefined_label': '预定义',
  'FLD_ShowOutput_label': '显示输出',
  'CAT_General': '一般',
  'CAT_Compilers': '编译器',
  'CAT_Shortcuts': '快捷键',
  'CAT_BeforeSave': '保存前',
  'CAT_AfterSave': '保存后',
  'CAT_Tools': '工具',
  'CAT_Project': '专案',
  'Extensions': '延伸',
  'UpperCase': '大写',
  'LowerCase': '小写',
  'Capitalize': '首字大写',
  'CamelCase': '驼峰式大小写',
  'DashCase': 'DashCase  DashCase',
  'CycleCase': 'CycleCase',
  'HtmlEncode': 'HtmlEncode',
  'HtmlDecode': 'HtmlDecode',
  'UrlEncode': 'UrlEncode',
  'UrlDecode': 'UrlDecode',
  'Join': '结合',
  'Split': '分裂',
  'Number': '编号',
  'Reverse': '反转',
  'Trim Leading': '移除行初空白',
  'Trim Trailing': '移除行尾空白',
  'Markdown Trim Trailing': 'Markdown 移除行尾空白',
  'Sort Ascending': '升序',
  'Sort Descending': '降序',
  'Remove Duplicates': '删除重复',
  'Remove Empty Lines': '删除空行',
  'Unix To Win': 'UNIX到Windows斜线',
  'Win To Unix': 'Ｗindows到UNIX斜线',
  'Single Slash To Double': '单斜线到双斜线',
  'Double To Single Slash': '双斜线到单斜线',
  'Single Quote To Double': '单引号到双引号',
  'Double To Single Quote': '双引号到单引号',
  'Toggle Quote': '切换引号',
  'Tab To Space': '跳位字元到空格',
  'Space To Tab': '空格到跳位字元',
  'Untag': 'Untag',
  'Tag': '标签',
  'Break Line At': '断行于',
  'Function JSDoc': 'Function JSDoc',
  'Declare JSLint Global': '声明JSLint Global',
  'Extractor': '抽出器',
  'Replace': '取代',
  'Open Url': '打开网址',
  'Web Search': '网站搜索',
  'Browse File': '浏览文件',
  'Recent Files': '最近的文件',
  'Copy Filename': '复制文件名',
  'Copy Fullname': '复制全路径名称',
  'Html Report': 'HTML报告',
  'Regex Tester': '正则表达式测试仪',
  'Compiler': '编译器(js6, scss)',
  'Commands': '命令',
  'Commands Mapper': '命令映像程式',
  'Options': '选项',
  'Execute': '执行'
});