#!/usr/bin/env python3
# Generated by Copilot
import os
import re
from datetime import datetime

def update_changelog_date():
    # Get the directory of the current file and navigate to ../debian
    current_dir = os.path.dirname(os.path.abspath(__file__))
    changelog_path = os.path.join(current_dir, '../debian/changelog')

    # Read the changelog file
    with open(changelog_path, 'r') as file:
        content = file.read()

    # Find the first date in the changelog
    date_pattern = re.compile(r'-- .+ <.+>  (.+)')
    match = date_pattern.search(content)
    
    if not match:
        print("No date found in the changelog.")
        return

    old_date = match.group(1)
    print(f"Old date found: {old_date}")

    # Get the current date and time in the same format
    current_date = datetime.now().strftime('%a, %d %b %Y %H:%M:%S +0000')
    print(f"Current date: {current_date}")

    # Replace the old date with the current date
    updated_content = content.replace(old_date, current_date, 1)

    # Write the updated content back to the file
    with open(changelog_path, 'w') as file:
        file.write(updated_content)

    print("Changelog date updated successfully.")

# Example usage
update_changelog_date()
