// this is automatic generated file. Edit i18n-dev.tsv and run node txt2nls.js

// ------------------------------------------------------------------------
// Copyright (c) 2016-2019 Alexandre Bento Freire. All rights reserved.
// Licensed under the MIT License+uuid License. See License.txt for details
// ------------------------------------------------------------------------

/* spell-checker: disable */
define({
  'HISTORY_HINT': '使用Ctrl + UP / DOWN來獲取歷史紀錄',
  'SPACETEXT_HINT': ' 使用 \\$ 來獲取行初空白與行尾空白',
  'SHORTCUT_HINT': '例如：Ctrl-Shift-U (win).  Cmd-Shift-U (mac)',
  'NEED_RESTART_MSG': '重新啟動後生效！',
  'DEVBY_MSG': '通過{0}開發',
  'EXTRACTOR_MSG': '寫出一個正則運算法<br>所有符合的項目將會複製到剪貼板<br>',
  'FLD_limaxcharsperline_label': '每行的最大值',
  'FLD_limaxcharsperline_hint': '設置0無自動換行',
  'FLD_maxcharsperline_label': '每行的最大值',
  'FLD_maxcharsperline_hint': '最小值為1',
  'FLD_tobreakwords_label': '斷詞',
  'FLD_tobreakwords_hint': '如果可以斷詞,設定為正確',
  'FLD_lihtmlparawrap_label': 'html tag wrap',
  'FLD_lihtmlparawrap_hint': '以此標籤包裹每個段落。例如：p',
  'FLD_linrparagraphs_label': '段落號碼',
  'FLD_linrparagraphs_hint': '最大值為100',
  'FLD_scss_label': 'scss編譯器',
  'FLD_scss_hint': '您必須先安裝sass。轉到http://sass-lang.com/',
  'FLD_scss_compass_label': 'Compass',
  'FLD_scss_sass_label': 'SCSS',
  'FLD_scss_autosave_hint': '自動保存',
  'FLD_js6_label': 'js6編譯器',
  'FLD_js6_hint': '您必須安裝nodejs，然後"npm install -g traceur"',
  'FLD_js6_autosave_hint': '自動保存',
  'FLD_js_label': 'JS編譯器',
  'FLD_js_hint': '您必須安裝nodejs，然後"npm install -g uglify-js"',
  'FLD_splitMarker_label': '分裂標記',
  'FLD_historySize_label': '歷史大小',
  'FLD_recentSize_label': '最近的大小',
  'FLD_showcxtedit_label': '按右鍵顯示編輯命令',
  'FLD_showcxtedit_hint': '需要重新加載才能生效',
  'FLD_startNum_label': '初始值',
  'FLD_numSep_label': '號碼後分離',
  'FLD_tabSize_label': '跳位字元大小',
  'FLD_find_label': '尋找',
  'FLD_replace_label': '取代',
  'FLD_replace_hint': '使用＃{d}＃，＃{d}＃，＃{d}＃，＃{<value> d}＃，＃{0 <value> d}＃為巨集編號',
  'FLD_startValue_label': '開始',
  'FLD_startValue_hint': '為無編號留空，因為它減慢過程而且只支持取代小的正則表達式子集。必須檢查正則表達式',
  'FLD_stepValue_label': '步驟',
  'FLD_iswordsonly_label': '全字',
  'FLD_iswordsonly_hint': '只有在不是正則表達式時運作',
  'FLD_isregexpr_label': '正則表達式',
  'FLD_isignorecase_label': '忽略大小寫',
  'FLD_isimultiline_label': '多線路',
  'FLD_isall_label': '全部取代',
  'FLD_isselonly_label': '選取範圍內',
  'FLD_isselonly_hint': '如果有已選擇的文本,取代已選擇的文本',
  'FLD_webSearch_label': '搜索引擎網址',
  'HDR_options_Field_label': '欄位',
  'HDR_options_Value_label': '值',
  'HDR_options_ExecOnSave_label': '保存後執行',
  'HDR_commandsmapper_Command_label': '命令',
  'HDR_commandsmapper_Hotkey_label': '熱鍵',
  'HDR_commandsmapper_Show on Menu_label': '顯示於主選單',
  'HDR_commandsmapper_Show on CtxMenu_label': '按右鍵後顯示',
  'FLD_Cmdline_label': '命令行',
  'FLD_Path_label': '路徑',
  'FLD_Predefined_label': '預定義',
  'FLD_ShowOutput_label': '顯示輸出',
  'CAT_General': '一般',
  'CAT_Compilers': '編譯器',
  'CAT_Shortcuts': '快捷鍵',
  'CAT_BeforeSave': '保存前',
  'CAT_AfterSave': '保存後',
  'CAT_Tools': '工具',
  'CAT_Project': '專案',
  'Extensions': '延伸',
  'UpperCase': '大寫',
  'LowerCase': '小寫',
  'Capitalize': '首字大寫',
  'CamelCase': '駝峰式大小寫',
  'DashCase': 'DashCase',
  'CycleCase': 'CycleCase',
  'HtmlEncode': 'HtmlEncode',
  'HtmlDecode': 'HtmlDecode',
  'UrlEncode': 'UrlEncode',
  'UrlDecode': 'UrlDecode',
  'Join': '結合',
  'Split': '分裂',
  'Number': '編號',
  'Reverse': '反轉',
  'Trim Leading': '移除行初空白',
  'Trim Trailing': '移除行尾空白',
  'Markdown Trim Trailing': 'Markdown 移除行尾空白',
  'Sort Ascending': '升序',
  'Sort Descending': '降序',
  'Remove Duplicates': '刪除重複',
  'Remove Empty Lines': '刪除空行',
  'Unix To Win': 'UNIX到Windows斜線',
  'Win To Unix': 'Ｗindows到UNIX斜線',
  'Single Slash To Double': '單斜線到雙斜線',
  'Double To Single Slash': '雙斜線到單斜線',
  'Single Quote To Double': '單引號到雙引號',
  'Double To Single Quote': '雙引號到單引號',
  'Toggle Quote': '切換引號',
  'Tab To Space': '跳位字元到空格',
  'Space To Tab': '空格到跳位字元',
  'Untag': 'Untag',
  'Tag': '標籤',
  'Break Line At': '斷行於',
  'Function JSDoc': 'Function JSDoc',
  'Declare JSLint Global': '聲明JSLint Global',
  'Extractor': '抽出器',
  'Replace': '取代',
  'Open Url': '打開網址',
  'Web Search': '網站搜索',
  'Browse File': '瀏覽文件',
  'Recent Files': '最近的文件',
  'Copy Filename': '複製文件名',
  'Copy Fullname': '複製全路徑名稱',
  'Html Report': 'HTML報告',
  'Regex Tester': '正則表達式測試儀',
  'Compiler': '編譯器(js6, scss)',
  'Commands': '命令',
  'Commands Mapper': '命令映像程式',
  'Options': '選項',
  'Execute': '執行'
});