#!/usr/bin/env bash
# --------------------------------------------------------------------
# Copyright (c) 2024 Alexandre Bento Freire. All rights reserved.
# Licensed under the GPL-2.0 license
# --------------------------------------------------------------------

# ------------------------------------------------------------------------
# Creates a plugin from a template. Expects [Caption and Plugin]
# ------------------------------------------------------------------------

SCRIPT_PATH="$(dirname $(realpath "$0"))"
cd "$SCRIPT_PATH/../usr/share/editortoix"
rm -rf pluma
cp -ar xed pluma
cd pluma/plugins
rm toix_proxy/toix_proxy_xed.py
find . -iname '*.py' -exec sed -i -E 's/GObject, Xed/GObject, Pluma/;s/toix_proxy_xed/toix_proxy_pluma/;s/ToIXProxyXed/ToIXProxyPluma/;s/Xed.Window/Pluma.Window/;s/(GPL-2.0 license)/\1\n# Generated by a script/' "{}" \;
echo "Generated Pluma Plugins from Xed"

cd ../..
cp -f gedit/plugins/toix_proxy/toix_proxy_gedit.py $TMPDIR/toix_proxy_gedit.py
rm -rf gedit
cp -ar xed gedit
cd gedit/plugins
rm toix_proxy/toix_proxy_xed.py
rm toix_proxy/toix_proxy_pluma.py
find . -iname '*.py' -exec sed -i -E "s/GObject, Xed/GObject, Gedit/;s/toix_proxy_xed/toix_proxy_gedit/;s/ToIXProxyXed/ToIXProxyGedit/;s/Xed.Window/Gedit.App/;s/window = GObject/app = GObject/;s/(GPL-2.0 license)/\1\n# Generated by a script/" "{}" \;
cp $TMPDIR/toix_proxy_gedit.py toix_proxy/toix_proxy_gedit.py
echo "Generated Gedit Plugins from Xed"
