#!/bin/sh
set -e

case "$1" in
    configure)
        echo "Running post-installation script"

        [ -n "$(logname 2>/dev/null)" ] && ORIGINAL_USER="$(logname)" || ORIGINAL_USER="$SUDO_USER"
        echo "ORIGINAL_USER:[$ORIGINAL_USER]" >/var/log/editortoix-postinst.log 2>&1

        if [ -n "$ORIGINAL_USER" ]; then
            PLUGINS="$(sudo -u "$ORIGINAL_USER" dconf read /org/x/editor/plugins/active-plugins)"
            echo $PLUGINS >>/var/log/editortoix-postinst.log 2>&1
        fi

        if [ -z "$2" ]; then
            if [ -n "$PLUGINS" ]; then
                case "$PLUGINS" in
                    *toix_*)
                        # Match: A contains "toix_"
                        ;;
                    *)
                        PLUGINS="${PLUGINS%]}"
                        for FOLDER in /usr/lib/x86_64-linux-gnu/xed/plugins/toix_*; do
                            FOLDER="$(basename $FOLDER)"
                            [ $FOLDER != "toix_proxy" ] && PLUGINS="$PLUGINS, '$FOLDER'"
                        done
                        PLUGINS="$PLUGINS]"
                        sudo -u "$ORIGINAL_USER" dconf write /org/x/editor/plugins/active-plugins "$PLUGINS"
                        echo $PLUGINS >>/var/log/editortoix-postinst.log 2>&1
                        echo "EditorToIX plugins activated"
                        ;;
                esac
            fi
        elif [ "$2" = "4.0.5" ]; then
            rm -rf "/usr/lib/x86_64-linux-gnu/xed/plugins/toix_trimright"
            if [ -n "$ORIGINAL_USER" ]; then
                PLUGINS="$(echo "$PLUGINS" | sed 's/trimright/trimtrailing/')"
                echo $PLUGINS >>/var/log/editortoix-postinst.log 2>&1
                sudo -u "$ORIGINAL_USER" dconf write /org/x/editor/plugins/active-plugins "$PLUGINS"
                echo "EditorToIX plugins activated"
            fi
        fi
        ;;
    *)
        exit 0
        ;;
esac

exit 0
